### ISSUE TITLE
Hi 你好，请问下有研究过ImageInput怎么使用吗？

### ISSUE THREAD

**Issue by yangjiamu** [Kirk-Wang/scaling-redux-apps#1]
你好，我看你对react admin研究的挺多的，我最近也在用react admin，但是我不知道怎么用ImageInput，主要是后段接收不知道该怎么处理，你能提供一些帮助吗？

**Comment by Kirk-Wang** [comment]
<img width="1280" alt="2018-10-15 11 32 59" src="https://user-images.githubusercontent.com/29172756/46928799-e0206700-d06e-11e8-82b3-443a53358792.png">

如果你使用的是 `simple` 例子中 dataProvider，那么你在后端紧紧的转换base64到图片文件而已。
列如后端 api 使用这个包(node.js) ---[base64-img](https://www.npmjs.com/package/base64-img)

```js
base64Img.img('data:image/png;base64,...', 'dest', '1', function(err, filepath) {});
```
当然还有很多类似的处理，你可以自行探索。
